name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run PWD
        run: lsb_release -a

      - name: Run php
        run: php check.php