name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: docker://yarimadam/php

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Check
        uses: docker://yarimadam/php
        run: php check.php
