name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: docker://yarimadam/php

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run PWD
        with:
          entrypoint: /bin/sh
          args: -c "pwd && ls -la"

      - name: Run php
        with:
          entrypoint: php
          args: check.php