name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run PWD
        uses: docker://yarimadam/php
        with:
          entrypoint: /bin/sh
          args: -c "pwd && ls -la"

      - name: Lsb Release
        uses: docker://yarimadam/php
        with:
          entrypoint: /usr/bin/lsb_release
          args: -a

      - name: Run php
        uses: docker://yarimadam/php
        with:
          entrypoint: php
          args: check.php